### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by rikace** [nwolverson/signalrprovider#1]
I am getting an error when I build project.
The error is located in "SignalRServerProvider" project > file "Provider.fs"
line 118 
           let definedTypes = tyInfo |> List.map makeHubType

The error description is here below:
Error   5   Type mismatch. Expecting a
    HubType list \* HubType list -> 'a  
but given a
    'b list -> 'c list  
The type 'HubType list \* HubType list' does not match the type ''a list'    C:\Temp\signalrprovider-master\SignalRServerProvider\Provider.fs    118 34  SignalRServerProvider

**Comment by nwolverson** [comment]
Aha! I killed this SignalRServerProvider in favour of using only 1 type provider & less complex solution for client hubs (as per current README).

I thought I removed this but I had just excluded it locally. Hopefully you can build now

**Comment by nwolverson** [comment]
Assume this was resolved?

**Comment by rikace** [comment]
Yes indeed.

I have presented in F# eXchange in London and I have also used the SignlRProvider. I have fixed in local the nested types issue, as soon as I am confident that it is working solid I will make  push request

Thanks
Riccardo
