### ISSUE TITLE
GetDefinedTypes only uses the Seq.last assembly

### ISSUE THREAD

**Issue by louthy** [nwolverson/signalrprovider#2]
Hi, I recently downloaded the latest source to try and get this up and running with SignalR and FunScript.  It looks like a great approach.  However I couldn't get it working with `Hubs.myHubName`.  It seemed nothing I did would pick up the types.  So after many hours of trying to change my build and where the dlls were built to, shuffling code around, etc.  I decided to put some logging into the type-provider itself to see what it was doing.

That's when I came across the `GetDefinedTypes` method in ReflectionProxy.fs

``` F#
    member this.GetDefinedTypes(assemblies : string seq)  = 
        let asm = assemblies 
        if (not (Seq.isEmpty asm)) then
            let clientAsm = loadAssemblyBytes (Seq.last asm)
            let types = clientAsm.ExportedTypes |> List.ofSeq
            let hubTypes = types |> findHubs
            let hubTypeInfo = hubTypes |> List.map makeHubType
            let clientHubDef name =
                findClientHubDefs types hubTypes name |> List.map (fun t -> (name, makeHubType t))
            let clientHubDefs = List.map fst hubTypeInfo |> List.collect clientHubDef
            (hubTypeInfo, clientHubDefs)
        else 
            ([], [])
```

It appears to only be using the last assembly in the list, and my logging confirmed this (in my case the last assembly didn't have any hubs in it and therefore none were returned).  

So I updated the code to search all assemblies (see below) and everything works correctly.  I can do a pull request with the changes if you like, but I thought I'd check-in to see if you have any comments, maybe I missed something?

``` F#
    member this.GetDefinedTypes(assemblies : string seq)  = 
        assemblies |> Seq.fold (fun (hubTypeInfoState, clientHubDefsState) asm ->
                      let clientAsm = loadAssemblyBytes asm
                      let types = clientAsm.ExportedTypes |> List.ofSeq
                      let hubTypes = types |> findHubs
                      let hubTypeInfo = hubTypes |> List.map makeHubType
                      let clientHubDef name =
                          findClientHubDefs types hubTypes name |> List.map (fun t -> (name, makeHubType t))
                      let clientHubDefs = List.map fst hubTypeInfo |> List.collect clientHubDef
                      (hubTypeInfo @ hubTypeInfoState, clientHubDefs @ clientHubDefsState)
                      )
                      ([], [])
```

**Comment by nwolverson** [comment]
Sorry didn't see notification of this issue. Yes, you're right it was only using the last assembly, I'm sure there must have been some reason to do this temporarily but never got fixed. 

Be great if you could go ahead and submit a PR.

**Comment by nwolverson** [comment]
Made change pretty much as above - but with `try` as I've seen `ExportedTypes` fail where those types reference unloaded assemblies (could probably improve this).
